### ISSUE TITLE
hardcoded parameter

### ISSUE THREAD

**Issue by AdrianS85** [impact-initiatives/cleaningtools#78]
Dear all,

I noticed that in function check_outliers() we have a parameter "uuid_column = "uuid", but it seems to be hardcoded as "uuid" in command:
```
cols_to_add_cleaning_log <- unique(c(cols_to_add_cleaning_log, 
    "uuid"))
```

Best,
Adrian

**Comment by yannsay-impact** [comment]
This should be renamed before.
![MicrosoftTeams-image (5)](https://github.com/impact-initiatives/cleaningtools/assets/79831444/7601c352-444d-43bf-bcc0-89d2179de29a)
