### ISSUE TITLE
Errors while installing the package. Dependencies not installing unhcrdesign, unhcrdown, riddle

### ISSUE THREAD

**Issue by twesigye10** [impact-initiatives/cleaningtools#84]
ERROR: dependency 'unhcrdesign' is not available for package 'unhcrdown'
ERROR: dependency 'unhcrdown' is not available for package 'riddle'
ERROR: dependency 'riddle' is not available for package 'cleaningtools'

**Comment by yannsay-impact** [comment]
cleaningtools depends on some external packages from UNCHR. After discusison and updating the correct dependencies, packages are installed correctly.
